### PR TITLE
Fix template paths

### LINKED ISSUE #26: Fix bug in table_template.erb reference
A user ran into this today:

    (erb):46:in `initialize': No such file or directory @ rb_sysopen - themes/table_template.erb (Errno::ENOENT)

I think it might be caused by my use of `File.new()` without specifying how that path is found (so it's relative to the context). It works on at least 2 machines, but not on one (all macOS), but definitely a bug that I need to work around

Fix the reference in both template files

### PR DESCRIPTION
**Pull request by jaydorsey**
During a previous refactor I introduced a bug with the path names for
templates. The command ONLY worked from the local folder where
env_compare gem code lived. Since this is where I did all my testing,
I didn't discover it until someone pointed it out.

This PR:

- Refactors how the ERB is referenced so we can include paths
- Renames the templates from `.erb` to `.html.erb`
- Makes the themes easier to include other erb files
- Changes the ENV call to an ENV.fetch to make the need to include that
  ENV more clear
- Closes #26

### CODE REVIEW

**Comment by smridge** [comment]
This is a beautiful cleanup! So far looks good to me, I will check and test to confirm nothing breaks on my end. Since this will be a new release the `** 0.1.3.pre.beta **` references should be removed from the `README`.

**Comment by smridge** [comment]
Tested and works as expected! Really nice!

**Review by smridge — APPROVED** [review]

**Comment by smridge** [comment]
I just realized the CHANGELOG should be updated also.

**Comment by jaydorsey** [comment]
> I just realized the CHANGELOG should be updated also.

Good idea. I'll add that to this commit!

**Pull request merged**
